/** Well-known kids IP / brands that must never appear in a listing-bound book. Case-insensitive, whole-word. */
export const BANNED_TERMS: readonly string[] = [
  "Disney",
  "Pixar",
  "Marvel",
  "Pokemon",
  "Pokémon",
  "Pikachu",
  "Paw Patrol",
  "Peppa",
  "Peppa Pig",
  "Bluey",
  "Frozen",
  "Elsa",
  "Anna and Elsa",
  "Mickey",
  "Minnie",
  "Barbie",
  "Hello Kitty",
  "Spider-Man",
  "Spiderman",
  "Batman",
  "Superman",
  "Sonic",
  "Mario",
  "Luigi",
  "Minecraft",
  "Lego",
  "Cocomelon",
  "Baby Shark",
  "Sesame Street",
  "Elmo",
  "Winnie the Pooh",
  "Peter Rabbit",
  "Shrek",
  "Minions",
  "Despicable Me",
  "Hot Wheels",
  "My Little Pony",
  "SpongeBob",
  "Dora the Explorer",
  "Thomas the Tank Engine",
  "Care Bears",
  "Snoopy",
  "Hulk",
  "Iron Man",
  "Star Wars",
  "Harry Potter",
  "Gabby's Dollhouse",
  "Roblox",
  "Fortnite",
  "Lilo and Stitch",
  "Moana",
  "Encanto",
];
