import type { INestApplication } from "@nestjs/common";
import { Test } from "@nestjs/testing";
import request from "supertest";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { AppModule } from "../src/app.module";

describe("Self-Knowledge API (e2e)", () => {
  let app: INestApplication;

  beforeAll(async () => {
    // No per-suite dir isolation needed: `vitest.setup.ts` already seeds a fresh,
    // per-test-file `ZIBBY_DATA_DIR` (from `apps/api/data-test`) before this file's
    // `AppModule` ever boots — the same read-only-endpoint pattern as `gates.e2e.test.ts`.
    const moduleRef = await Test.createTestingModule({ imports: [AppModule] }).compile();
    app = moduleRef.createNestApplication();
    await app.init();
  });

  afterAll(async () => {
    await app.close();
  });

  const server = () => app.getHttpServer();

  it("composes a fresh snapshot with sections + an ISO generatedAt", async () => {
    const res = await request(server()).get("/api/self-knowledge").expect(200);

    expect(typeof res.body.markdown).toBe("string");
    expect(res.body.markdown).toContain("# Self-Knowledge");
    expect(res.body.markdown).toContain("<!-- AUTO:AGENTS:START -->");
    expect(Number.isNaN(Date.parse(res.body.generatedAt))).toBe(false);
    expect(typeof res.body.drift).toBe("boolean");
    expect(res.body.sections).toMatchObject({
      agents: expect.any(Number),
      pipelines: expect.any(Number),
      gateRules: expect.any(Number),
      channels: expect.any(Number),
    });
    // The data-test fixtures seed at least one agent/pipeline/gate rule.
    expect(res.body.sections.agents).toBeGreaterThan(0);
    expect(res.body.sections.channels).toBeGreaterThan(0);
  });

  it("reports no drift — the committed fixture note is kept in sync with the fixture catalog", async () => {
    // `apps/api/data-test/vault/knowledge/self-knowledge.md` is committed and
    // regenerated by `pnpm self-knowledge:generate` (the pre-commit hook + CI
    // enforce it), so a boot over the seeded fixture data root must see no drift.
    const res = await request(server()).get("/api/self-knowledge").expect(200);
    expect(res.body.drift).toBe(false);
  });
});
