import { chromium } from "/home/user/z.i.b.b.y/node_modules/.pnpm/playwright@1.60.0/node_modules/playwright/index.mjs";
import { pathToFileURL } from "node:url"; import path from "node:path";
const url = pathToFileURL(path.resolve("scratchpad/orb-preview/index.html")).href;
const b = await chromium.launch({ executablePath:"/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader","--ignore-gpu-blocklist"] });
const page = await b.newPage({ viewport:{width:1280,height:800} });
await page.goto(url); await page.waitForTimeout(2400);
await page.evaluate(()=>window.setDock([["r1","koder","Kodér → build app","agent"],["r2","delivery","Delivery pipeline","pipeline"],["r3","researcher","Researcher → sources","agent"]]));
await page.waitForTimeout(3200);
await page.screenshot({path:"scratchpad/orb-preview/t5-dock2.png"});
await b.close(); console.log("done");
